name: example
description: A new Flutter project.

publish_to: "none"
version: 4.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screen_lock:
    path: ../
  local_auth: ^2.1.7
  platform: ^3.1.3

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
