name: flutter_screen_lock
description: Provides the ability to lock the screen on ios and android.
  Biometric authentication can be used in addition to passcode.
homepage: https://github.com/naoki0719/flutter_screen_lock
version: 9.0.1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  analyzer: ^4.7.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
